### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by pietrushnic** [notro/rpi-build#10]
Hi @notro,
I have two questions about rpi-build:

* is it possible to build custom sha from raspberrypi/linux ?
* is possible to attach own config file other than patching existing config using Rakefile, like we did it in `rpi-bcm2835` ?

Or maybe I should look into other tools. I have to back to those workflow, because of my current project.

Best Regards,
pietrushnic

**Comment by notro** [comment]
> is it possible to build custom sha from raspberrypi/linux ?

Set this variable:
```ruby
VAR["RASPBERRYPI_LINUX_REF"]
```

> is possible to attach own config file

rpi-build will run the config target set with LINUX_DEFCONFIG.
Default: https://github.com/notro/rpi-build-stdlib/blob/master/rpi-linux.rb#L41
Target: https://github.com/notro/rpi-build/blob/master/targets.rake#L75

So you would have to do something like this:
```ruby
release :whatever [:dependencies] do
#this is run before the dependencies
end

# second release action
release :whatever do
  #this is run after the dependencies

  # clear out :config actions
  Rake::Task[:config].clear

  target :config do
    cp PATH, workdir('linux/.config')
  end
end
```

> Or maybe I should look into other tools

AFAIK there is Raspberry Pi support in buildroot and yocto. That might be a better choice since you can use the aquired knowledge on other platforms as well.

**Comment by pietrushnic** [comment]
Great! Many thanks for those hints.
